# @package hydra
defaults:
  - override job_logging: colorlog
  - override hydra_logging: colorlog

job:
  chdir: false

job_logging:
  handlers:
    file: 
      filename: ${hydra.runtime.output_dir}/hydra.log


run:
    dir: ./runs/${job_name}/${task}/${now:%Y%m%d_%H%M%S}
sweep:
  dir: ./sweeps/${job_name}/${now:%Y%m%d_%H%M%S}
  subdir: ${task}/${oc.select:backbone_model,any}/${hydra.job.num}