# Shared configuration for Protein Language Models
# This file should never be used directly in training configs

defaults:
  - default

# Common PLM parameters
max_length: 1024
batch_size: 1

# Default cache directory pattern (will be overridden by specific models)
cache_dir: "weights/${model_name}"

# Common embedding output structure
embedding_types:
  - "${model_key}"  # Will be resolved to actual model name

levels:
  - "AA"  # Amino acid (residue) level
  - "PR"  # Protein level